package com.springboot.qunawan.dao;

import com.springboot.qunawan.pojo.Placeontrip;

import java.util.List;

public interface PlaceontripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table placeontrip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table placeontrip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int insert(Placeontrip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table placeontrip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    Placeontrip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table placeontrip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    List<Placeontrip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table placeontrip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int updateByPrimaryKey(Placeontrip record);
}