package com.springboot.qunawan.dao;

import com.springboot.qunawan.pojo.Traffic;

import java.util.List;

public interface TrafficMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int insert(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    Traffic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    List<Traffic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int updateByPrimaryKey(Traffic record);
}