package com.springboot.qunawan.dao;

import com.springboot.qunawan.pojo.Trip;

import java.util.List;

public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    Trip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    List<Trip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int updateByPrimaryKey(Trip record);
}