package com.springboot.qunawan.dao;

import com.springboot.qunawan.pojo.Trippicture;

import java.util.List;

public interface TrippictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int insert(Trippicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    Trippicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    List<Trippicture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    int updateByPrimaryKey(Trippicture record);
}