package com.springboot.qunawan.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer trip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.orders
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.place
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.hotel
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer hotel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.service
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer traffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.usefull
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer usefull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.useless
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer useless;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user
     *
     * @return the value of comment.user
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user
     *
     * @param user the value for comment.user
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.trip
     *
     * @return the value of comment.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.trip
     *
     * @param trip the value for comment.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTrip(Integer trip) {
        this.trip = trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.orders
     *
     * @return the value of comment.orders
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.orders
     *
     * @param orders the value for comment.orders
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.place
     *
     * @return the value of comment.place
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.place
     *
     * @param place the value for comment.place
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.hotel
     *
     * @return the value of comment.hotel
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getHotel() {
        return hotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.hotel
     *
     * @param hotel the value for comment.hotel
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setHotel(Integer hotel) {
        this.hotel = hotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.service
     *
     * @return the value of comment.service
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.service
     *
     * @param service the value for comment.service
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setService(Integer service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.traffic
     *
     * @return the value of comment.traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.traffic
     *
     * @param traffic the value for comment.traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.time
     *
     * @return the value of comment.time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.time
     *
     * @param time the value for comment.time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.usefull
     *
     * @return the value of comment.usefull
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getUsefull() {
        return usefull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.usefull
     *
     * @param usefull the value for comment.usefull
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setUsefull(Integer usefull) {
        this.usefull = usefull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.useless
     *
     * @return the value of comment.useless
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getUseless() {
        return useless;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.useless
     *
     * @param useless the value for comment.useless
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setUseless(Integer useless) {
        this.useless = useless;
    }
}