package com.springboot.qunawan.pojo;

public class Commentpicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentpicture.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentpicture.comment
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentpicture.name
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentpicture.data
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentpicture.id
     *
     * @return the value of commentpicture.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentpicture.id
     *
     * @param id the value for commentpicture.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentpicture.comment
     *
     * @return the value of commentpicture.comment
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentpicture.comment
     *
     * @param comment the value for commentpicture.comment
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentpicture.name
     *
     * @return the value of commentpicture.name
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentpicture.name
     *
     * @param name the value for commentpicture.name
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentpicture.data
     *
     * @return the value of commentpicture.data
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentpicture.data
     *
     * @param data the value for commentpicture.data
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}