package com.springboot.qunawan.pojo;

public class Dates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.schedule
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.title
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.num
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.detail
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.hotel
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String hotel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.meal
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String meal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dates.traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String traffic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.id
     *
     * @return the value of dates.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.id
     *
     * @param id the value for dates.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.schedule
     *
     * @return the value of dates.schedule
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.schedule
     *
     * @param schedule the value for dates.schedule
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setSchedule(Integer schedule) {
        this.schedule = schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.title
     *
     * @return the value of dates.title
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.title
     *
     * @param title the value for dates.title
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.num
     *
     * @return the value of dates.num
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.num
     *
     * @param num the value for dates.num
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.detail
     *
     * @return the value of dates.detail
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.detail
     *
     * @param detail the value for dates.detail
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.hotel
     *
     * @return the value of dates.hotel
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getHotel() {
        return hotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.hotel
     *
     * @param hotel the value for dates.hotel
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setHotel(String hotel) {
        this.hotel = hotel == null ? null : hotel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.meal
     *
     * @return the value of dates.meal
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getMeal() {
        return meal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.meal
     *
     * @param meal the value for dates.meal
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setMeal(String meal) {
        this.meal = meal == null ? null : meal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dates.traffic
     *
     * @return the value of dates.traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dates.traffic
     *
     * @param traffic the value for dates.traffic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTraffic(String traffic) {
        this.traffic = traffic == null ? null : traffic.trim();
    }
}