package com.springboot.qunawan.pojo;

public class Ordercontact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.orders
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.contact
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.type
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.id
     *
     * @return the value of ordercontact.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.id
     *
     * @param id the value for ordercontact.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.orders
     *
     * @return the value of ordercontact.orders
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.orders
     *
     * @param orders the value for ordercontact.orders
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.contact
     *
     * @return the value of ordercontact.contact
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.contact
     *
     * @param contact the value for ordercontact.contact
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setContact(Integer contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.type
     *
     * @return the value of ordercontact.type
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.type
     *
     * @param type the value for ordercontact.type
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}