package com.springboot.qunawan.pojo;

public class Placeontrip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column placeontrip.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column placeontrip.place
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column placeontrip.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer trip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column placeontrip.id
     *
     * @return the value of placeontrip.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column placeontrip.id
     *
     * @param id the value for placeontrip.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column placeontrip.place
     *
     * @return the value of placeontrip.place
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column placeontrip.place
     *
     * @param place the value for placeontrip.place
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column placeontrip.trip
     *
     * @return the value of placeontrip.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column placeontrip.trip
     *
     * @param trip the value for placeontrip.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTrip(Integer trip) {
        this.trip = trip;
    }
}