package com.springboot.qunawan.pojo;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.p1
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Float p1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.p2
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Float p2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.level
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.p1
     *
     * @return the value of position.p1
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Float getP1() {
        return p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.p1
     *
     * @param p1 the value for position.p1
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setP1(Float p1) {
        this.p1 = p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.p2
     *
     * @return the value of position.p2
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Float getP2() {
        return p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.p2
     *
     * @param p2 the value for position.p2
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setP2(Float p2) {
        this.p2 = p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.level
     *
     * @return the value of position.level
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.level
     *
     * @param level the value for position.level
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}