package com.springboot.qunawan.pojo;

public class Themeontrip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column themeontrip.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column themeontrip.theme
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column themeontrip.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer trip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column themeontrip.id
     *
     * @return the value of themeontrip.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column themeontrip.id
     *
     * @param id the value for themeontrip.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column themeontrip.theme
     *
     * @return the value of themeontrip.theme
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column themeontrip.theme
     *
     * @param theme the value for themeontrip.theme
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTheme(Integer theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column themeontrip.trip
     *
     * @return the value of themeontrip.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column themeontrip.trip
     *
     * @param trip the value for themeontrip.trip
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setTrip(Integer trip) {
        this.trip = trip;
    }
}