package com.springboot.qunawan.pojo;

public class Traffic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.go_point
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String goPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.go_time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String goTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.return_point
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String returnPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.return_time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String returnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.id
     *
     * @return the value of traffic.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.id
     *
     * @param id the value for traffic.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.go_point
     *
     * @return the value of traffic.go_point
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getGoPoint() {
        return goPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.go_point
     *
     * @param goPoint the value for traffic.go_point
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setGoPoint(String goPoint) {
        this.goPoint = goPoint == null ? null : goPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.go_time
     *
     * @return the value of traffic.go_time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getGoTime() {
        return goTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.go_time
     *
     * @param goTime the value for traffic.go_time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setGoTime(String goTime) {
        this.goTime = goTime == null ? null : goTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.return_point
     *
     * @return the value of traffic.return_point
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getReturnPoint() {
        return returnPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.return_point
     *
     * @param returnPoint the value for traffic.return_point
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setReturnPoint(String returnPoint) {
        this.returnPoint = returnPoint == null ? null : returnPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.return_time
     *
     * @return the value of traffic.return_time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.return_time
     *
     * @param returnTime the value for traffic.return_time
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setReturnTime(String returnTime) {
        this.returnTime = returnTime == null ? null : returnTime.trim();
    }
}