package com.springboot.qunawan.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.youbian
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String youbian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shen
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String shen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shi
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String shi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qu
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private String qu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    private byte[] pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.youbian
     *
     * @return the value of user.youbian
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getYoubian() {
        return youbian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.youbian
     *
     * @param youbian the value for user.youbian
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setYoubian(String youbian) {
        this.youbian = youbian == null ? null : youbian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shen
     *
     * @return the value of user.shen
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getShen() {
        return shen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shen
     *
     * @param shen the value for user.shen
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setShen(String shen) {
        this.shen = shen == null ? null : shen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shi
     *
     * @return the value of user.shi
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shi
     *
     * @param shi the value for user.shi
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setShi(String shi) {
        this.shi = shi == null ? null : shi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qu
     *
     * @return the value of user.qu
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public String getQu() {
        return qu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qu
     *
     * @param qu the value for user.qu
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setQu(String qu) {
        this.qu = qu == null ? null : qu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pic
     *
     * @return the value of user.pic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public byte[] getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pic
     *
     * @param pic the value for user.pic
     *
     * @mbggenerated Mon Jun 17 11:23:14 CST 2019
     */
    public void setPic(byte[] pic) {
        this.pic = pic;
    }
}